name: arabella
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.1.1
  easy_localization: ^3.0.1
  provider: ^6.0.3
  carousel_slider: ^4.1.1
  flutter_markdown: ^0.6.10+3
  shared_preferences: ^2.0.15
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/

    - assets/chapters/ar/1-history/lessons/
    - assets/chapters/ar/1-history/quiz/
    - assets/chapters/en/1-history/lessons/
    - assets/chapters/en/1-history/quiz/

    - assets/chapters/ar/2-geography/lessons/
    - assets/chapters/ar/2-geography/quiz/
    - assets/chapters/en/2-geography/lessons/
    - assets/chapters/en/2-geography/quiz/

    - assets/chapters/ar/3-culture/lessons/
    - assets/chapters/ar/3-culture/quiz/
    - assets/chapters/en/3-culture/lessons/
    - assets/chapters/en/3-culture/quiz/

    - assets/chapters/ar/4-tourism_and_archaeological_sites/lessons/
    - assets/chapters/ar/4-tourism_and_archaeological_sites/quiz/
    - assets/chapters/en/4-tourism_and_archaeological_sites/lessons/
    - assets/chapters/en/4-tourism_and_archaeological_sites/quiz/

    - assets/chapters/ar/5-education/lessons/
    - assets/chapters/ar/5-education/quiz/
    - assets/chapters/en/5-education/lessons/
    - assets/chapters/en/5-education/quiz/


    - assets/images/chapters/1-history/cover_images/
    - assets/images/chapters/1-history/lessons_images/
    - assets/images/chapters/1-history/quiz_images/

    - assets/images/chapters/2-geography/cover_images/
    - assets/images/chapters/2-geography/lessons_images/
    - assets/images/chapters/2-geography/quiz_images/

    - assets/images/chapters/3-culture/cover_images/
    - assets/images/chapters/3-culture/lessons_images/
    - assets/images/chapters/3-culture/quiz_images/

    - assets/images/chapters/4-tourism_and_archaeological_sites/cover_images/
    - assets/images/chapters/4-tourism_and_archaeological_sites/lessons_images/
    - assets/images/chapters/4-tourism_and_archaeological_sites/quiz_images/

    - assets/images/chapters/5-education/cover_images/
    - assets/images/chapters/5-education/lessons_images/
    - assets/images/chapters/5-education/quiz_images/


    - assets/images/badges/
    - assets/images/drawer_background/
    - assets/images/drawer_circular/