name: arabella
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.1.1
  easy_localization: ^3.0.1
  provider: ^6.0.3
  flutter_markdown: ^0.6.10+5
  shared_preferences: ^2.0.15
  confetti: ^0.7.0
  google_maps_flutter: ^2.1.10
  google_maps_flutter_web: ^0.4.0+2
  animated_background: ^2.0.0
  image: ^3.2.0
  liquid_progress_indicator: ^0.4.0
  url_launcher: ^6.1.5
  flutter_colorpicker: ^1.0.3
  path_provider: ^2.0.11
  archive: ^3.3.1
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "ic_launcher"
  image_path: "assets/images/ic_launcher.png"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
  adaptive_icon_background: "#FFF9C4"
  min_sdk_android: 20
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/drawer_circular/
    - assets/images/markers/

    - assets/maps/

    - assets/translations/